usb: phy: msm: Fix the compilation error with GCC 5.1
gcc 5.1 has -wbool-compare option which detected the code
in the usb phy driver doing the wrong comparision because
the code was missing the proper parenthesis and could
result into the phy->state always becoming the
boolean value Vs the enum value it supposed to be
while checking it in the if condition.

Following was the warning for reference:

phy-msm-usb.c:1392:19: warning: comparison of constant '3' with boolean expression is always false [-Wbool-compare]

However this is due to typo in code that got introduced by
commit 2370d3bb74188 ("USB: phy: msm: Remove ACA and SRP, HNP
related code")

Change-Id: I63a78f7cab88ff0ac6fcfd02ca865d626ebaf482
Signed-off-by: Trilok Soni <tsoni@codeaurora.org>
Signed-off-by: Manu Gautam <mgautam@codeaurora.org>